### ISSUE TITLE
yargs-parser Vulnerable to Prototype Pollution

### ISSUE THREAD

**Issue by CollapsedMetal** [stefanocudini/configYml#5]
Hello @stefanocudini !

First of all... thanks for this fork!👌

Is there any chance to fix this vulnerability?

![image](https://user-images.githubusercontent.com/5317311/232157700-990ea895-3fae-48a4-9a2e-9c850e122e92.png)

Greetings!

**Comment by CollapsedMetal** [comment]
Fixed by adding some overrides to my package.json

<pre>
{
  "name": "project",
  "version": "1.0.0",
  "description": "project",
  "main": "config.js",
  "scripts": {
    "start": "node server.js"
  },
  "author": "nobody",
  "license": "ISC",
  "dependencies": {
    "@stefcud/configyml": "^1.2.3",
  },
  "overrides": {
    "yargs": "^17.7.1",
    "yargs-parser": "^21.1.1"
  }
}

**Comment by stefanocudini** [comment]
can you send a PR ? many tnks

**Comment by CollapsedMetal** [comment]
Done!
